import type { Expense, User } from "./types";

export const mockUser: User = {
  name: "Jane Doe",
  email: "jane.doe@example.com",
};

export const mockExpenses: Expense[] = [
  {
    id: "exp_1",
    type: 'expense',
    amount: 12.5,
    category: "Food",
    date: new Date("2024-07-15"),
    description: "Lunch at The Daily Grind",
    paymentMethod: 'Cash',
  },
  {
    id: "exp_2",
    type: 'expense',
    amount: 250.0,
    category: "Travel",
    date: new Date("2024-07-14"),
    description: "Flight ticket to San Francisco",
    paymentMethod: 'Card',
  },
  {
    id: "exp_3",
    type: 'expense',
    amount: 75.99,
    category: "Shopping",
    date: new Date("2024-07-14"),
    description: "New pair of shoes",
    paymentMethod: 'Card',
  },
  {
    id: "exp_4",
    type: 'expense',
    amount: 120.0,
    category: "Bills",
    date: new Date("2024-07-13"),
    description: "Electricity bill",
    paymentMethod: 'Online',
  },
  {
    id: "exp_5",
    type: 'expense',
    amount: 45.0,
    category: "Entertainment",
    date: new Date("2024-07-12"),
    description: "Movie tickets for two",
    paymentMethod: 'Card',
  },
  {
    id: "exp_6",
    type: 'expense',
    amount: 88.2,
    category: "Groceries",
    date: new Date("2024-07-11"),
    description: "Weekly grocery shopping",
    paymentMethod: 'Cash',
  },
  {
    id: "exp_7",
    type: 'expense',
    amount: 22.5,
    category: "Transportation",
    date: new Date("2024-07-10"),
    description: "Monthly metro pass",
    paymentMethod: 'Card',
  },
  {
    id: "exp_8",
    type: 'expense',
    amount: 35.0,
    category: "Food",
    date: new Date("2024-06-28"),
    description: "Dinner with friends",
    paymentMethod: 'Card',
  },
  {
    id: "exp_9",
    type: 'expense',
    amount: 550.0,
    category: "Bills",
    date: new Date("2024-06-25"),
    description: "Monthly rent",
    paymentMethod: 'Online',
  },
  {
    id: "exp_10",
    type: 'expense',
    amount: 63.5,
    category: "Health",
    date: new Date("2024-06-22"),
    description: "Pharmacy purchase",
    paymentMethod: 'Cash',
  },
];
